### ISSUE TITLE
itsrdf:taAnnotatorRef : insertion of attribute in html markup after round-tripping

### ISSUE THREAD

**Issue by katia-vistatec** [freme-project/basic-services#100]
When e-Internationalization processes some input, it may add this attribute to the outer most tag. Like the “html” tag when we process a whole HTML document.

**Comment by katia-vistatec** [comment]
Which should be the value?Can you give me an example? @fsasaki

**Comment by fsasaki** [comment]
See here https://www.w3.org/TR/its20/#its-tool-annotation
and 
https://www.w3.org/TR/its20/#EX-its-tool-annotation-html5-1
the example shows tool annotation after machine translation. For tool annotation after e-entity one needs to add text-analysis|tool-identifier to the attribute, separated via "|". It is also important to just add these  values and not override an existing value from e.g. machine translation. It is not possible to have several values of the same type, e.g. several machine translation tool identifiers.

**Comment by katia-vistatec** [comment]
Is there a service I can use currently that produces a nif file with entity annotations?

**Comment by fsasaki** [comment]
> Is there a service I can use currently that produces a nif file with entity annotations?
sure, that is FREME NER or dbpedia spotlight. So in e-internationalisation you can check: is the output coming from dbpedia spotlight? Then add text-analytics|dbpedia-spotlight to the attribute.

**Comment by katia-vistatec** [comment]
dbpedia spotlight I can use locally so it is ok for debugging but yesterday did not work.

**Comment by fsasaki** [comment]
can you use freme ner instead?

**Comment by katia-vistatec** [comment]
I use locally broker-local and there isn't freme-ner in broker-local.

**Comment by fsasaki** [comment]
OK. for testing, can you have an HTTP request to freme-ner?

2016-09-02 15:14 GMT+02:00 katia-vistatec <notifications@github.com>:

**Comment by jnehring** [comment]
DBpedia spotlight does not work occasionaly. Right now it works so you can use it now.

I added FREME NER to the freme-local installation. But it is only a proxy endpoint and proxies to freme-ner-dev. I think that e-Internationalization is therefore not executed on the local installation, but on the remote installation of freme-ner-dev so it might not be suitable for development of e-Internationalization.

**Comment by jnehring** [comment]
this is done
