### ISSUE TITLE
[pipelines] change POST and PUT pipeline

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#102]
The body of the request should contain the serialized requests only. Parameter "description" can be set via query string anyways. In addition to this, parameter "label" needs to be moved from the json field in the body to a required query string parameter.

This needs changes in

* POST / PUT /pipelines/templates controller
* API documentation of these two endpoints

**Comment by ArneBinder** [comment]
This is implemented. @jnehring can we close it?

**Comment by jnehring** [comment]
Thanks Arne. I leave this ticket open to remind me of the database change in the next release.
