### ISSUE TITLE
Allow TIKA to handle HTTP POST body (not only multipart request)

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#108]
Goal of this issue: allow usage of TIKA with HTTP POST body, without multipart request.

See current implementation using TIKA here
https://github.com/freme-project/basic-services/issues/75

**Comment by jnehring** [comment]
[NIFConverter controller](https://github.com/freme-project/basic-services/blob/master/controllers/nifconverter/src/main/java/eu/freme/bservices/controllers/nifconverter/NifConverterController.java) should have this behaviour:

* It will become active when informat=TIKAFile (this is the current behaviour)
* Check the content-type header, if it is a multipart request then execute the old code.
* if it is not a multipart request, then take the whole request body as input file for conversion to NIF. TIKA needs the filename to determine the file type. So in this case the user needs to submit an additional parameter "filename".

**Comment by fsasaki** [comment]
thanks, Jan. Is there an example for this in the documentation?

**Comment by jnehring** [comment]
> thanks, Jan. Is there an example for this in the documentation?

First @bgrusdt will implement the feature, then we will add it to the documentation.

**Comment by bgrusdt** [comment]
The basic version which fails for pdfs is still there, but now the tika-filter can be used when filename is set and informat=TIKAFile.

**Comment by jnehring** [comment]
Does not work for me.

**Comment by bgrusdt** [comment]
In curl, -T should be used, in Postman I just used the binary option for the body. The following curl should work. I attached the test file I used.
[testdocx.docx](https://github.com/freme-project/basic-services/files/732092/testdocx.docx)

```
curl -X POST -T testdocx.docx "http://api.freme-project.eu/current/e-translation/tilde?filename=testdocx.docx&informat=TIKAFile&source-lang=en&target-lang=de"
```

**Comment by jnehring** [comment]
Ah ok I forgot the parameter filename. Thanks for the info.

This feature is documented here: https://freme-project.github.io/knowledge-base/freme-for-api-users/gettingStarted_API-users.html

So we can close this.
