### ISSUE TITLE
missing sparql converter

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#109]
I had created a while ago a sparlq filter
freme-ner-output-as-web-annotation
see the request referenced here
https://lists.w3.org/Archives/Public/public-annotation/2016Apr/0041.html
it seems the filter is gone (both in freme dev / freme life) - is there the change of having a local copy if it somewhere?

**Comment by jnehring** [comment]
I recovered it from a database backup from july and wrote it to FREME DEV and FREME LIVE.

http://api-dev.freme-project.eu/current/toolbox/convert/manage/freme-ner-output-as-web-annotation

Should this converter be part of [initialising freme](api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html) ?

**Comment by fsasaki** [comment]
great, thanks. Yes, that should be in initialising freme.

**Comment by fsasaki** [comment]
p.s. this request

http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Berlin&informat=text&outformat=turtle&language=en&dataset=dbpedia&mode=all&filter=freme-ner-output-as-web-annotation


works, for freme live I get an error

http://api.freme-project.eu/current/e-entity/freme-ner/documents?input=Berlin&informat=text&outformat=turtle&language=en&dataset=dbpedia&mode=all&filter=freme-ner-output-as-web-annotation

> result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements

**Comment by jnehring** [comment]
The filter was installed twice. I deleted one of them. Now your request works.

@bgrusdt please add the filter to [initialising sparql converters](https://raw.githubusercontent.com/freme-project/freme-packages/master/broker-local/src/main/resources/init-sparqlconverter.sql)

**Comment by fsasaki** [comment]
Great, thanks!

**Comment by jnehring** [comment]
reopening the issue to remind @bgrusdt to add the filter to initialising freme.

**Comment by jnehring** [comment]
We will update the initialising freme sql files once in the end of the project and not for each filter separately. So this issue is finished.
