### ISSUE TITLE
[urlsupport filter] missing content-type causes error

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/basic-services#112]
Try this request (but use Postman, curl sets a default content-type):

```
POST http://api-dev.freme-project.eu/current/toolbox/nif-converter?intype=url&input=http://beautifulberlin.blogspot.de/2009/07/short-history-of-berlin.html
```
I get:
```
{"timestamp":1475585730677,"status":500,"error":"Internal Server Error","exception":"java.lang.NullPointerException","message":"No message available","path":"/toolbox/nif-converter"}
```

This is because the page at `http://beautifulberlin.blogspot.de/2009/07/short-history-of-berlin.html` does not send a content-type header back, so the content-type variable is set to `null` [here](https://github.com/freme-project/basic-services/blob/master/filters/urlsupport-filter/src/main/java/eu/freme/bservices/filters/urlsupport/UrlSupportFilter.java#L82), but checked later with `isEmpty()`.
In general, I prefere to use `Strings.isNullOrEmpty(...)` to avoid such a problem. @jnehring Or is this bad in any way?

Furthermore, it looks like there are cases that `ModifyRequestBodyWrapper` is initialised with `contentType=""`, but ModifyRequestBodyWrapper defaults to `text/html` only, if it is `null`, not an empty string, see [here](https://github.com/freme-project/basic-services/blob/master/filters/urlsupport-filter/src/main/java/eu/freme/bservices/filters/urlsupport/ModifyRequestBodyWrapper.java#L97).

**Comment by jnehring** [comment]
> In general, I prefere to use Strings.isNullOrEmpty(...) to avoid such a problem. @jnehring Or is this bad in any way?

Strings.isNullOrEmpty is fine. In general you should treat null values.

I think the current behaviour is fine, except for it should not crash. When no content-type is specified then the system should treat it as turtle. The API call works when I specify informat=text/html so we need to deal with the nullpointerexception only.

Does the API documentation mention that intype=url guesses the input format from the content type header of the web page? I did not know about this behaviour. We should note it somewhere.

**Comment by jnehring** [comment]
This behaviour is documented in the full api documentation. Please add an example curl request and a short explanation to [getting started for api users](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html) and link from the note in the api documentation to the article.

**Comment by bgrusdt** [comment]
I added the [description](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html) , linked to it from the [full api documentation](https://api-dev.freme-project.eu/doc/api-doc/full.html#/General_Information) and changed the code such that no NullPointerException is thrown anymore.

**Comment by jnehring** [comment]
thank you!

**Comment by bgrusdt** [comment]
@jnehring We decided to change the behaviour such that now text/turtle is used as default Content-Type if the user does not specify it. I have changed this.  Now the call, 
```
POST http://api-dev.freme-project.eu/current/toolbox/nif-converter?intype=url&input=http://beautifulberlin.blogspot.de/2009/07/short-history-of-berlin.html
```
results in a 'Error parsing NIF-Input' - Error which is appropriate.

I have also adapted the [documentation](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html).

**Comment by jnehring** [comment]
Thank you! Btw. it is not necessary to add a dynamic URL to each CURL example that uses freme-dev in the dev documentation and freme-live in the live documentation. You can point directly to the live version. But you can leave it like it is, it causes no problem. I just want to save you the extra work.

**Comment by bgrusdt** [comment]
Thank you @jnehring, thats good to know.
