### ISSUE TITLE
Internal server error with post processing filter

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#116]
See attached file and below request.

> curl -X POST -H "Content-type: text/turtle" -d@out.txt "https://api-dev.freme-project.eu/current/toolbox/convert/documents/count-domains?informat=turtle&outformat=csv"
> [out.txt](https://github.com/freme-project/basic-services/files/524901/out.txt)

**Comment by jnehring** [comment]
I can reproduce the bug. 

It works when I remove informat and outformat parameters from URL and specify the accept header:

``` 
curl -X POST -H "Content-type: text/turtle"  -header 'Accept: text/comma-separated-values' -d@out.txt "https://api-dev.freme-project.eu/current/toolbox/convert/documents/count-domains"
```

The stack trace:

```
ERROR   2016-10-13 09:46:13,626 [http-nio-8089-exec-6] eu.freme.bservices.controllers.sparqlconverters.SparqlConverterController  -
ERROR   2016-10-13 09:46:13,626 [http-nio-8089-exec-6] eu.freme.common.exception.ExceptionHandlerService  - Request: http://rv1443.1blu.de:8089/toolbox/convert/documents/count-domains raised
eu.freme.common.exception.FREMEHttpException
        at eu.freme.bservices.controllers.sparqlconverters.SparqlConverterController.filter(SparqlConverterController.java:162)
        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by fsasaki** [comment]
I still get the attached error with the attached curl request.

[curl-plus-output.txt](https://github.com/freme-project/basic-services/files/526986/curl-plus-output.txt)

**Comment by fsasaki** [comment]
I still get the error message, with the request attached here https://github.com/freme-project/basic-services/issues/116#issuecomment-253491180

**Comment by jnehring** [comment]
Sorry I assigned you too quickly and Jenkins was still updating the installation. Please try again.

informat and outformat are not valid parameters for the sparql filters. You have to set the informat and outformat via header.

I added some input validation, now your curl request produces

```
{
  "exception": "eu.freme.common.exception.BadRequestException",
  "path": "/toolbox/convert/documents/count-domains",
  "message": "Invalid value \"*/*\" for Accept header.",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1476360625408
}
```

@fsasaki does this solve your problem?

**Comment by jnehring** [comment]
When I do the API request 

curl -X POST -H "Content-type: text/turtle"  --header 'Accept: text/comma-separated-values' -d@out.txt "https://api-dev.freme-project.eu/current/toolbox/convert/documents/count-domains"

The request does not finish and it produces a lot of warnings like this

```
WARN    2016-12-05 16:03:34,569 [http-nio-8089-exec-1] com.hp.hpl.jena.sparql.expr.NodeValue  - Datatype format exception: "<sourceDesc><p/></sourceDesc>"^^rdf:XMLLiteral
```

**Comment by bgrusdt** [comment]
@jnehring @fsasaki 
The request does finish, but only after about 5 minutes. The input file is quite large, it has about 25000 lines, when the data is provided in chunks of about 5000 lines, the answer is returned quickly.

The warning is because of this value:
``` "<sourceDesc><p/></sourceDesc>"^^rdf:XMLLiteral . ``` which is inside:
```
:       a                 dcat:Dataset , tbx:MartifHeader ;
        dc:source         "" ;
        dct:type          "TBX" ;
        tbx:encodingDesc  "<p type=\"XCSURI\">http://www.ttt.org/oscarstandards/tbx/TBXXCS.xcs</p>"^^rdf:XMLLiteral ;
        tbx:sourceDesc    "<sourceDesc><p/></sourceDesc>"^^rdf:XMLLiteral .
```
