### ISSUE TITLE
change references to blu.de

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#117]
In several parts of the code and of asserts (e.g. sparql queries) there are references to the current hosting service blu.de . e.g.

> curl -X GET  "http://api.freme-project.eu/current//e-link/templates" 

produces a template with id 301 which has the LDF endpoint

> http://rv2622.1blu.de:5000/dbpedia-types

the data that is stored at blu.de needs to be moved and the references like the above need to be updated. This task is not specific to e-link, but all services and assets in general.

**Comment by jnehring** [comment]
Good point. I think we need to

1) Create a proxy redirect on freme live, something like https://api.freme-projet.eu/triplestore -> http://rv2622.1blu.de:5000 . 
2) Update all references to rv2622 server with this proxy redirect in the e-Link templates. Above URL would turn into https://api.freme-projet.eu/triplestore/dbpedia-types
3) Do a full text search in the source codes and the database dumps for the string "1blu" to detect other references
4) Ask adapt research centre to create a similar proxy redirect.

**Comment by jnehring** [comment]
I worked on this:

* I created a proxy redirect from https://api.freme-project.eu/sparql to http://rv2622.1blu.de:8890/sparql
* Updated the documentation homepage where possible

Still pending

* https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/howto-release.html . This will be done in https://github.com/freme-project/freme-project.github.io/issues/321
* The documentation homepage has some references to the LDF endpoint that refer to a 1blu server. I did not change these.
* Tell ADAPT about the redirect

**Comment by jnehring** [comment]
done
