### ISSUE TITLE
Removed dependency on e-capitalization

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#118]
The unit test of urlsupport-filter used the e-capitalization filter from freme-examples. This created a circular dependency between freme-examples and basic-services. I removed the dependency on e-capitalization and commented out the unit test in urlsupport-filter in [this commit](https://github.com/freme-project/basic-services/commit/d36a6814b2f673bd4d93b420dab862305186edc4).

This issue is a reminder to re-activate the unit test after basic services and freme examples have been released.

**Comment by jnehring** [comment]
e-capitalization is now released on maven central

**Comment by bgrusdt** [comment]
This is done.
