### ISSUE TITLE
Implement input from URL

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#28]
According to the [NIF specifications](http://persistence.uni-leipzig.org/nlp2rdf/specification/api.html) allow input from URL. This is a basic service "url-input". This is a filter that becomes active when "intype=url" is set. In this case it will transform the request to "intype=text". The new request will have as body the content of the URL.

Please implement this in a streaming fashion so it does not consume too much memory.

**Comment by jnehring** [comment]
basic version is working. next steps

* intype parameter can has value "url". Then the url is read from either "input" or "i".
* in the unit tests, please remove dependencies from external apis. the url input can come from the test helpers mockup endpoint. Use the e-Capitalization endpoint.
* Create one test with HTML document `<p>hello world</p>` and one with a plaintext document `hello world`.

**Comment by bgrusdt** [comment]
It is implemented, [see here](https://github.com/freme-project/basic-services/tree/master/filters/urlsupport-filter/src/main). @jnehring  can you have a look at it please? Thanks.
I have included the filter into freme-parent. Shall I include the dependency  in any freme-package?

**Comment by jnehring** [comment]
Thank you. Please add this functionality to the freme packages

* freme-full
* broker-local
* broker-dev

Then I can test it.

**Comment by bgrusdt** [comment]
Its done, @jnehring  you can test it.

**Comment by jnehring** [comment]
Can you please provide a cURL example how to use the service? I tried this but I get an InternalServerError:

curl -X POST -H "Content-Type: text/html" -H "input: http%3A%2F%2Fwww.tagesschau.de%2Fausland%2Fmallorca-tourismus-101.html" -H "Cache-Control: no-cache" -H "Postman-Token: 3f8d4dc8-8ca9-9e0e-1c8c-71689a59e07e" -d '' "http://api-dev.freme-project.eu/current/toolbox/nif-converter?intype=url"

**Comment by bgrusdt** [comment]
```
curl -X POST -H "Content-Type: text/html" "http://api-dev.freme-project.eu/current/toolbox/nif-converter?intype=url&input=http://www.tagesschau.de/ausland/mallorca-tourismus-101.html"
```

**Comment by jnehring** [comment]
Oh right sorry now I see that my cURL was wrong.

In case a user does not specify a URL when intype=url, can you please throw a BadRequestException with appropriate error message instead of internal server error?

Further please make a suggestion how to document this. I think the general information section in http://api-dev.freme-project.eu/doc/api-doc/full.html is a good place for this information.

**Comment by bgrusdt** [comment]
I added the BadRequestException. @jnehring  Can you test it again please?
The [NIF-specification](http://persistence.uni-leipzig.org/nlp2rdf/specification/api.html) suggests that there is also the value *file* , which means that the input is retrieved from a local file. Shall we implement this as well? 

My suggestion:
* intype
  * determines how the input is accessed or retrieved
  * possible values
    * direct (default): The input is either read from the body of the request or from the input parameter 
    * url: The input  is retrieved from the url specified in the 'input' or 'i' parameter  
    * (file: The input is read from a local file)

**Comment by jnehring** [comment]
I think the "file" intype is applicable for command line applications only and is not applicable for us. Your suggestion looks good, please add it to the documentation without the "file" value.

**Comment by bgrusdt** [comment]
Ok. This is done.

**Comment by fsasaki** [comment]
sorry to ask the same question again ;) is this documented in the API documentation?

**Comment by bgrusdt** [comment]
Yes the description is in the new documentation, under [General Information](http://freme-project.github.io/api-doc/full.html#/General_Information).

**Comment by fsasaki** [comment]
Great, thanks.

2016-08-18 14:58 GMT+02:00 bgrusdt <notifications@github.com>:
