### ISSUE TITLE
Anything to NIF converter

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#29]
Please implement an anything to NIF converter. You can send plaintext or the input formats that e-Internationalisation supports to the endpoint and it returns NIF. Use the API endpoint /toolbox/nif-converter

**Comment by ArneBinder** [comment]
Which tests should be added?

**Comment by ArneBinder** [comment]
Implemented controller + tests.

**Comment by ArneBinder** [comment]
TODO: add further tests
* formats supported by e-Internalisation (except xml)

**Comment by jnehring** [comment]
I think that e-Internationalisation should work out of the box because of the e-Internationalisation filter. Or do you mean you just need to write tests for e-Internationalisation?

**Comment by ArneBinder** [comment]
just the tests

**Comment by jnehring** [comment]
Please add documentation to the [full API documentation](http://api-dev.freme-project.eu/doc/api-doc/full.html). Rename section "postprocessing" to "Toolbox" and add the new API endpoint there.

**Comment by ArneBinder** [comment]
Added tests for xliff and html, the odt test does not work. Is the odt conversion in e-internalisation broken?

**Comment by jnehring** [comment]
I dont know if odt conversion is broken. I will try it out.

**Comment by jnehring** [comment]
I created a test ODT and send it to the freme-dev api. I used e-Translation. It worked fine. So I think that odt conversion is not broken in e-internationalisation.

**Comment by ArneBinder** [comment]
seems to work, but the the odt test still fails ([it](https://github.com/freme-project/basic-services/blob/master/controllers/nifconverter/src/test/java/eu/freme/bservices/controllers/nifconverter/NifConverterControllerTest.java#L89) is excluded)

**Comment by ArneBinder** [comment]
Wait for #34

**Comment by ArneBinder** [comment]
Done.
