### ISSUE TITLE
Allow configuration of URLs by ManagedResourceController

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#31]
Right now all owned resources are managed by URLs like `/e-link/manage`. Before this used to be `/e-link/templates`. Now some codes are broken because the URLs have changed. Please add the functionality to configure the URLs of ManagedResourceController and change the URLs to how they were before.

I think we need to change back the URLs of these endpoints (maybe more?):

* manage e-link templates
* manage filter
* manage pipelines

**Comment by jnehring** [comment]
Please update the documentation also: http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/implementing-restricted-access-to-database-resources.html

**Comment by ArneBinder** [comment]
Implemented the functionality, but the wrong endpoints start on broker-dev. I assume that there is a version issue, my IDE loads still common2 into my local maven repo. @jnehring any ideas?

**Comment by jnehring** [comment]
> Implemented the functionality, but the wrong endpoints start on broker-dev. I assume that there is a version issue, my IDE still loads common2 into my local maven repo and if I delete it, it works. @jnehring any ideas?

The tilde-services project pulled in the old common2 artifact. I fixed this. Please check if it works now.

> Should the URLs be read from the application.properties file? If yes, via which keys?

This is not necessary. It is ok when this configuration is done in the source code.

**Comment by ArneBinder** [comment]
so can we close this? The documentation is already updated.
