### ISSUE TITLE
[internationalization] odt conversion generates strange uris

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/basic-services#34]
The generic URI `http://freme-project.eu/~okapi-23_OpenOfficeFilter_8046756076162932045.tmp`
causes problems for tests (see #29), it changes every api call although the input stays the same.

Full response:
```
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .

<http://freme-project.eu/~okapi-23_OpenOfficeFilter_8046756076162932045.tmp/#char=0,12>
        a               nif:Context , nif:RFC5147String , nif:String ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "12"^^xsd:nonNegativeInteger ;
        nif:isString    "Hello World!"@en ;
        dc:identifier   "1" .
```

**Comment by jnehring** [comment]
I think that this URI is ok and it is only a problem for the unit tests. In general it is ok that e-Internationalisation generates a new URI for each API call.

@ArneBinder can you change the unit tests in a way that it can cope with these changing URIs?

**Comment by ArneBinder** [comment]
OK, I will try this.

**Comment by ArneBinder** [comment]
Done.
