### ISSUE TITLE
Make load balancer configurable

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#38]
In branch "cloud basic services" in project "load balancer" make the load balancing configuration configurable using these options:

```
load-balancer.identifier.local-endpoint: ...
load-balancer.identifier.target-endpoint: ...
load-balancer.identifier.service-name: ...
```

Implement this in LoadBalancerConfiguration.getProxyConfigurations

**Comment by ArneBinder** [comment]
implemented.
