### ISSUE TITLE
mime type for XML

### ISSUE THREAD

**Issue by m1ci** [freme-project/basic-services#41]
While testing the XML to RDF conversion using the NIF converter I noticed that only text/xml is supported, application/xml not.

application/xml should be added as valid mime for XML

**Comment by jnehring** [comment]
@ArneBinder please implement

**Comment by ArneBinder** [comment]
@jnehring the artifact (common) was not deployed successful, it is already versioned as release (0.6). How to proceed?

**Comment by jnehring** [comment]
I solved the problem of deployment by changing the version number of FREME common to 0.7-SNAPSHOT.
@ArneBinder is this feature implemented?

**Comment by ArneBinder** [comment]
Yes.
