### ISSUE TITLE
ODT not accepted by the NIF converter

### ISSUE THREAD

**Issue by m1ci** [freme-project/basic-services#43]
For 
`curl -X POST --header "Content-Type: application/x-openoffice" --header "Accept: text/turtle" -d @test.txt "http://api-dev.freme-project.eu/current/toolbox/nif-converter" -v
`
where the document is [test.txt](https://github.com/freme-project/basic-services/files/225598/test.txt)

I get `HTTP/1.1 406 Not Acceptable`, however it should be valid and accepted.

**Comment by ArneBinder** [comment]
@m1ci this is a curl issue. Please try this:

```
curl -X POST -H "Content-Type: application/x-openoffice" --data-binary "@test.txt" "http://api-dev.freme-project.eu/current/toolbox/nif-converter"
```

**Comment by m1ci** [comment]
right, you are right, closing the issue
