### ISSUE TITLE
[pipelining][POST /chain/id] use in-/outformat and content-type/accept header values

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/basic-services#48]
At the moment, the pipelining endpoint discards these informations. It should work like @andish proposed [here](https://github.com/freme-project/Documentation/issues/171#issuecomment-221842976).

Furthermore, I would recommend to forward **all** headers and parameters which were send to the pipeline endpoint to the first request (and overwrite defined ones in the pipeline) except outformat and Accept header, which go to the last. What do you think?

**Comment by jnehring** [comment]
Good idea! Please implement.

**Comment by ArneBinder** [comment]
implemented.
