### ISSUE TITLE
[internalisation-filter] examine if xml roundtripping would work

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/basic-services#49]
Check if adding the xml mime type to roundtrippingFormats will enable roundtripping for xml.

**Comment by ArneBinder** [comment]
This works, xml was added to the roundtripping formats in the internalization-filter.

**Comment by jnehring** [comment]
I reopen this issue so we do not forget it. We still need to consider if we can claim that XML works as format for roundtripping.

**Comment by ArneBinder** [comment]
I already tried [this file](https://github.com/freme-project/basic-services/blob/master/internationalization/src/test/resources/nifConversion/src1/test1.xml). But we can check other xml files, if you want.

**Comment by jnehring** [comment]
I tried some XML files. It works, also on complicated XML files like our pom.xml files.

This XML file:

```
<?xml version="1.0" encoding="UTF-8"?>
<note>
	<to>Tove</to>
	<from>Jani</from>
	<heading>Welcome to Berlin!</heading>
</note>
```

it gets converted to this turtle:

```
@prefix xsd:   
<http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: 
    <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   
        <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix dc:    
            <http://purl.org/dc/elements/1.1/> .


            <http://freme-project.eu/#char=0,4>
        a                     nif:String , nif:RFC5147String , nif:Phrase ;
        nif:anchorOf          "Tove"@en ;
        nif:beginIndex        "0"^^xsd:nonNegativeInteger ;
        nif:endIndex          "4"^^xsd:nonNegativeInteger ;
        nif:referenceContext  
                <http://freme-project.eu/#char=0,28> ;
        dc:identifier         "1" .


                    <http://freme-project.eu/#char=5,9>
        a                     nif:String , nif:RFC5147String , nif:Phrase ;
        nif:anchorOf          "Jani"@en ;
        nif:beginIndex        "5"^^xsd:nonNegativeInteger ;
        nif:endIndex          "9"^^xsd:nonNegativeInteger ;
        nif:referenceContext  
                        <http://freme-project.eu/#char=0,28> ;
        dc:identifier         "2" .


                            <http://freme-project.eu/#char=10,28>
        a                     nif:String , nif:RFC5147String , nif:Phrase ;
        nif:anchorOf          "Welcome to Berlin!"@en ;
        nif:beginIndex        "10"^^xsd:nonNegativeInteger ;
        nif:endIndex          "28"^^xsd:nonNegativeInteger ;
        nif:referenceContext  
                                <http://freme-project.eu/#char=0,28> ;
        dc:identifier         "3" .


                                    <http://freme-project.eu/#char=0,28>
        a               nif:String , nif:Context , nif:RFC5147String ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "28"^^xsd:nonNegativeInteger ;
        nif:isString    "Tove Jani Welcome to Berlin!"@en .
```

I see one bug: The converter assumes that all text is English. I do not know how it came to this conclusion. I think it just marks all text as English which is wrong.

Further we need to update the [e-internatoinalisation documentation](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/eInternationalisation.html) which states "At the moment the round-tripping is only available for HTML documents. ".

I also tested roundtipping with e-Entity service. It produced a valid output document.

We should add to the roundtripping article that it roundtripping HTML and XML can only write named entity annotations and named entity links in the output document.

**Comment by ArneBinder** [comment]
Furthermore, the roundtripping test with long-html.html seems to be broken.

**Comment by ArneBinder** [comment]
> Further we need to update the e-internatoinalisation documentation which states "At the moment the round-tripping is only available for HTML documents. ".

@jnehring why do we not include xml?

I added the sentence `It is restricted to write named entity annotations and named entity links into the output document.` and added `english` to `At the moment the round-tripping is only available for english HTML documents.`

> I see one bug: The converter assumes that all text is English

This might be a bug in the [InternalisationApi](https://github.com/freme-project/basic-services/blob/master/internationalization/src/main/java/eu/freme/bservices/internationalization/api/InternationalizationAPI.java). I opened [this issue](https://github.com/freme-project/basic-services/issues/53).

**Comment by jnehring** [comment]
>> Further we need to update the e-internatoinalisation documentation which states "At the moment the round-tripping is only available for HTML documents. ".

> @jnehring why do we not include xml?

This is a misunderstanding. The current text does not mention XML and there we need to update the text like "At the momennt round-tripping is available for HTML and XML documents".

**Comment by ArneBinder** [comment]
> This is a misunderstanding. The current text does not mention XML and there we need to update the text like "At the momennt round-tripping is available for HTML and XML documents".

Oh, of course, I will fix this.

**Comment by ArneBinder** [comment]
Fixed. @jnehring does [the article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/eInternationalisation.html) look ok now? Can we close this?

**Comment by jnehring** [comment]
Well done, thanks!
