### ISSUE TITLE
SPARQL filter does not work

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#50]
```
curl -X POST -d @data.txt --header "Content-Type: application/rdf-xml" "http://api-dev.freme-project.eu:8084/toolbox/filter/documents/extract-entities-only?informat=rdf-xml&outformat=json"
```

with this [data.txt](https://github.com/freme-project/basic-services/files/304437/data.txt)

produces

```
{
"timestamp":1465378560769,
"status":500,
"error":"Internal Server Error",
"exception":"eu.freme.common.exception.InternalServerErrorException",
"message":"No message available","path":"/toolbox/filter/documents/extract-entities-only"
}
```

**Comment by ArneBinder** [comment]
Please use the correct endpoint: /toolbox/**convert**/documents/extract-entities-only. Where did you find this depricated call?

**Comment by jnehring** [comment]
The deprecated call causes a bug in FREME workflow editor (see linked issue).  Thanks for the hint, with the updated endpoint the API call works.
