### ISSUE TITLE
improvement for start_server.sh

### ISSUE THREAD

**Issue by PeterBourgonje** [freme-project/basic-services#54]
We're using this piece of the FREME code in the DKT project and sometimes there's a bit of confusion when the start_server.sh script happily reports 'Started FREME', also when it failed (e.g. it's just an echo, doesn't check for anything).
 I'm no bash wizard and the following would have to be tested first, but maybe you can consider something like:

```
SCRIPT=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT")
cd $BASEDIR"/.."

if [ -a config/start-properties ]
  then
        source config/start-properties
fi

nohup java -cp "./*:config" $START_ARGS org.springframework.boot.loader.JarLauncher > /dev/null 2>&1 &
echo $! > config/pid.txt
process_with_pid_is_running=0
if [ -f config/pid.txt ]
then
    pid=$( cat config/pid.txt )
    pid=10401
	for i in {0..20..1}
    	    do
	    
	    if ps -p $pid > /dev/null
		then
		process_with_pid_is_running=1
		break
	    fi
	    sleep 0.1
    done
fi

if [ $process_with_pid_is_running -eq 1 ]
    then
    echo "Started FREME"
else
    echo "Could not find process id. Please check logs."
fi
```

Where, if it didn't find a process with the relevant process id after 1 second (or longer, if the sleep time is increased a bit), it just reports this instead.

**Comment by jnehring** [comment]
Good idea! Two comments:

>     echo "Could not find process id. Please check logs."

I think a better message is: "FREME failed to start. Please check the logs".

Your script is a good step in the right direction. We could further improve it. Instead of directing the scripts output directly to /dev/null we could scan it for the text "FREME has been started in xyz seconds". When this message is displayed, then FREME started correctly. The script outputs first "Starting FREME" and "FREME has been started" when the line was detected in the output.

**Comment by jnehring** [comment]
@PeterBourgonje I tested your script. It always reports that FREME did not start, but it starts. Did the script work on your machine?

**Comment by PeterBourgonje** [comment]
I'm stupid. I left the following (debugging) line in there in the version above, hard setting the pid:
pid=10401
If I take that out, it works for me. That is; it reports it started. If I change the actual starting line to something erroneous (starting with "ohup" for example, instead of "nohup"), it reports that it didn't start. Probably there are a couple more scenario's though for which I haven't/couldn't check. (Cannot think of one at the moment, but I will give it some more thought...)

**Comment by jnehring** [comment]
>  I left the following (debugging) line in there in the version above, hard setting the pid:
pid=10401

I removed the line, now it works. I also changed the error message and increased the timeout to 20 seconds for people with slow laptops.

> Probably there are a couple more scenario's though for which I haven't/couldn't check. 

We will find out. I merged your code in the master branch and it already started successfully the freme-dev server. So I think this issue is solved.
