### ISSUE TITLE
[e-internationalisation] enhance output

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#56]
Currently the output has

> &lt;span its-term="yes">some term&lt;/span>

but not 
> &lt;span its-term="yes“ its-term-info-ref="@@@">some term&lt;/span>
 
Would it be possible to store in its-term-info-ref the NIF subject URI for the term - I am making something up below:

> &lt;span its-term="yes“ its-term-info-ref="http://freme-project.eu/#char=0,9">some term&lt;/span>
 
With this URI

> http://freme-project.eu/#char=0,9

a tool easily can easily refer to other term related information (term ID, domain ID, related lexicon, translation suggestions).

**Comment by andish** [comment]
This could be a solution as ```its-term-info-ref``` can't hold multiple term references.
But in this case including the NIF object in HTML is mandatory (e.g. in ```script``` tag), because the NIF document will not be resolvable via URL. While there where direct term URIs, including the real terms in the document was optional because the term content could be downloaded from server ```term.tilde.com/term/...```

**Comment by fsasaki** [comment]
> This could be a solution as its-term-info-ref can't hold multiple term references.

Indeed. 

> But in this case including the NIF object in HTML is mandatory (e.g. in script tag), because the NIF document will not be resolvable via URL. 

Indeed.

**Comment by katia-vistatec** [comment]
Hi Felix, could you give me an example input file and the curl?

**Comment by fsasaki** [comment]
Sure, see example input with CURL and output, with content type text/turtle.

- Felix



2016-07-13 15:57 GMT+02:00 katia-vistatec <notifications@github.com>:

> Hi Felix, could you give me an example input file and the curl?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freme-project/basic-services/issues/56#issuecomment-232362887>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABH5AvxU1uIjDJiBgl39Q6yiC_zLu8Ahks5qVO7JgaJpZM4JIl2i>
> .
>

@prefix cc:    <http://creativecommons.org/ns#> .
@prefix :      <https://term.tilde.com/terms/> .
@prefix void:  <http://rdfs.org/ns/void#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix its:   <http://www.w3.org/2005/11/its> .
@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix tbx:   <http://tbx2rdf.lider-project.eu/tbx#> .
@prefix decomp: <http://www.w3.org/ns/lemon/decomp#> .
@prefix dct:   <http://purl.org/dc/terms/> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix ontolex: <http://www.w3.org/ns/lemon/ontolex#> .
@prefix ldr:   <http://purl.oclc.org/NET/ldr/ns#> .
@prefix odrl:  <http://www.w3.org/ns/odrl/2/> .
@prefix dcat:  <http://www.w3.org/ns/dcat#> .
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .

<http://freme-project.eu/#char=36,40>
        a                     nif:RFC5147String ;
        nif:anchorOf          "city"@en ;
        nif:annotationUnit    [ rdfs:label           "city"@en ;
                                itsrdf:taConfidence  1
                              ] ;
        nif:beginIndex        "36"^^xsd:nonNegativeInteger ;
        nif:endIndex          "40"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://freme-project.eu/#char=0,52> ;
        itsrdf:term           "yes" ;
        itsrdf:termInfoRef    :652483 , :2739744 .

:nl     a                 ontolex:Lexicon ;
        ontolex:entry     :stad-nl ;
        ontolex:language  <http://www.lexvo.org/page/iso639-3/dut> .

:       a                 dcat:Dataset , tbx:MartifHeader ;
        dc:source         "" ;
        dct:type          "TBX" ;
        tbx:encodingDesc  "<p type=\"XCSURI\">http://www.ttt.org/oscarstandards/tbx/TBXXCS.xcs</p>"^^rdf:XMLLiteral ;
        tbx:sourceDesc    "<sourceDesc><p/></sourceDesc>"^^rdf:XMLLiteral .

<https://term.tilde.com/terms/city-en#Sense>
        ontolex:reference  :652483 , :2739744 .

<https://term.tilde.com/terms/stad-nl#CanonicalForm>
        ontolex:writtenRep  "stad"@nl .

<https://term.tilde.com/terms/stad-nl#Sense>
        ontolex:reference  :652483 , :2739744 .

<https://term.tilde.com/terms/city-en#CanonicalForm>
        ontolex:writtenRep  "city"@en .

<http://freme-project.eu/#char=20,52>
        a                     nif:String , nif:RFC5147String , nif:Phrase ;
        nif:anchorOf          "\nWelcome to the city of Prague.\n"@en ;
        nif:beginIndex        "20"^^xsd:nonNegativeInteger ;
        nif:endIndex          "52"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://freme-project.eu/#char=0,52> ;
        dc:identifier         "3" .

:652483  a                skos:Concept ;
        rdfs:comment      "environmental policy"@en ;
        tbx:definition    "\"Term used generically today to denote any urban form but applied particularly to large urban settlements. There are, however, no agreed definitions to separate a city from the large metropolis or the smaller town. (Source: GOOD)\""@en ;
        tbx:subjectField  <https://term.tilde.com/domains/TaaS-1100> , <https://term.tilde.com/domains/5206> .

:stad-nl  a                    ontolex:LexicalEntry ;
        tbx:reliabilityCode    3 ;
        <http://www.lexinfo.net/ontology/2.0/lexinfo#termType>
                <http://www.lexinfo.net/ontology/2.0/lexinfo#fullForm> ;
        ontolex:canonicalForm  <https://term.tilde.com/terms/stad-nl#CanonicalForm> ;
        ontolex:language       <http://www.lexvo.org/page/iso639-3/dut> ;
        ontolex:sense          <https://term.tilde.com/terms/stad-nl#Sense> .

<http://freme-project.eu/#char=0,9>
        a                     nif:String , nif:RFC5147String , nif:Phrase ;
        nif:anchorOf          "\nExample\n"@en ;
        nif:beginIndex        "0"^^xsd:nonNegativeInteger ;
        nif:endIndex          "9"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://freme-project.eu/#char=0,52> ;
        dc:identifier         "1" .

:2739744  a               skos:Concept ;
        tbx:subjectField  <https://term.tilde.com/domains/TaaS-1100> , <https://term.tilde.com/domains/52> .

<http://freme-project.eu/#char=0,52>
        a               nif:String , nif:RFC5147String , nif:Context ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "52"^^xsd:nonNegativeInteger ;
        nif:isString    "\nExample\n \nExample\n \nWelcome to the city of Prague.\n"@en .

:en     a                 ontolex:Lexicon ;
        ontolex:entry     :city-en ;
        ontolex:language  <http://www.lexvo.org/page/iso639-3/eng> .

<http://freme-project.eu/#char=10,19>
        a                     nif:String , nif:RFC5147String , nif:Phrase ;
        nif:anchorOf          "\nExample\n"@en ;
        nif:beginIndex        "10"^^xsd:nonNegativeInteger ;
        nif:endIndex          "19"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://freme-project.eu/#char=0,52> ;
        dc:identifier         "2" .

:city-en  a                    ontolex:LexicalEntry ;
        tbx:reliabilityCode    3 ;
        <http://www.lexinfo.net/ontology/2.0/lexinfo#termType>
                <http://www.lexinfo.net/ontology/2.0/lexinfo#fullForm> ;
        ontolex:canonicalForm  <https://term.tilde.com/terms/city-en#CanonicalForm> ;
        ontolex:language       <http://www.lexvo.org/page/iso639-3/eng> ;
        ontolex:sense          <https://term.tilde.com/terms/city-en#Sense> .

curl -X POST -H "Content-Type: text/html" -d '<!DOCTYPE html> <html lang='"'"'en' >   <head>     <meta charset='utf-8' > <title>Example</title>   </head>         <body> <h1>Example</h1>    <p>Welcome to the city of Prague.</p>   </body> </html>' "http://api-dev.freme-project.eu/current/e-terminology/tilde?informat=text/html&outformat=text/turtle&source-lang=en&target-lang=nl"

**Comment by katia-vistatec** [comment]
Hi Felix,
the itsrdf:term           "yes" ; 
itsrdf:termInfoRef    :652483 , :2739744 .

are added by e-terminology service or am I wrong?

**Comment by fsasaki** [comment]
Hi Katia, yes, that is correct.

**Comment by katia-vistatec** [comment]
Hi Felix, but they are added without passing for internationalization API?

**Comment by fsasaki** [comment]
Hi Katia,

 itsrdf:term "yes" ;
itsrdf:termInfoRef :652483 , :2739744 .

is added in the NIF representation - that is independent of the
internationalization
API.

2016-07-14 15:35 GMT+02:00 katia-vistatec <notifications@github.com>:

**Comment by katia-vistatec** [comment]
Ok. I have to process the Model associated to the nif in the response body and then set the response.

**Comment by katia-vistatec** [comment]
[out2.txt](https://github.com/freme-project/basic-services/files/366383/out2.txt)
[out.txt](https://github.com/freme-project/basic-services/files/366384/out.txt)

**Comment by katia-vistatec** [comment]
curl -X POST --header "Content-Type: text/html" --data "@terminology.html" --header "Accept: text/turtle" "http://localhost:8080/e-terminology/tilde?informat=text/html&outformat=text/turtle&source-lang=en&target-lang=nl" > out.txt
curl -X POST --header "Content-Type: text/html" --data "@terminology.html" --header "Accept: text/html" "http://localhost:8080/e-terminology/tilde?informat=text/html&outformat=text/html&source-lang=en&target-lang=nl" > out2.txt

**Comment by katia-vistatec** [comment]
Hi Felix,
using these curls I obtain those outputs for turtle and html outformat.
There's the enrichment (termInfoRef with the subject Uri value) but still an already existing error ("of Prague." is outputed as "rague.")_ I have to see why this happen.

**Comment by fsasaki** [comment]
Thanks a lot, Katja. I just tried this

curl -X POST -H "Content-Type: text/html" -H "Accept: text/html" -H
"Cache-Control: no-cache" -H "Postman-Token:
bcb0da9a-5f76-80ca-3e94-d9867964e632" -d '<!DOCTYPE html> <html
lang='"'"'en' >   <head>     <meta charset='utf-8' > <title>Example</title>
  </head>         <body> <h1>Example</h1>    <p>Welcome to the city of
Prague.</p>   </body> </html>' "
http://api-dev.freme-project.eu/current/e-terminology/tilde?informat=text/html&outformat=text/html&source-lang=en&target-lang=nl
"

but got the old output. I see in your request localhost as the domain, so
the new code is probably not yet on the server.

2016-07-15 18:07 GMT+02:00 katia-vistatec <notifications@github.com>:

**Comment by katia-vistatec** [comment]
No. It isn't

**Comment by katia-vistatec** [comment]
Pushed the changes to repository. The attribute its-term-info-ref appears if the right version of internationalization artifact is taken, as declared in freme-parent pom.xml.

**Comment by katia-vistatec** [comment]
The output I obtain is:
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">	<title>Example</title>   </head>         <body>	<h1>Example</h1>	<p>Welcome to the city <span its-term-info-ref="<http://freme-project.eu/#char=36,40>" its-term="yes">city</span>rague.</p> </body></html>

**Comment by katia-vistatec** [comment]
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">	<title>Example</title>   </head>         <body>	<h1>Example</h1>	<p>Welcome to the city <span its-term-info-ref="<http://freme-project.eu/#char=36,40>" its-term="yes">city</span>rague.</p> </body></html>

**Comment by katia-vistatec** [comment]
<p>Welcome to the city <span its-term-info-ref="<http://freme-project.eu/#char=36,40>" its-term="yes">city</span>rague.</p>

**Comment by katia-vistatec** [comment]
Anyway the output is not exactly the correct one because in the nif skeleton there aren't new lines  while there are in the enriched nif. I think the same happen for issue #60 and so I am inserting new lines in the nif skeleton also.

**Comment by fsasaki** [comment]
Thanks, Katia. With below curl request

curl -X POST -H "Content-Type: text/html" -H "Accept: text/html" -H
"Cache-Control: no-cache" -H "Postman-Token:
d1c39cd2-1328-0aa2-09b9-d2723b48d345" -d '<!DOCTYPE html> <html
lang='"'"'en' >   <head>     <meta charset='utf-8' > <title>Example</title>
  </head>         <body> <h1>Example</h1>    <p>Welcome to the capital of
Germany!</p>   </body> </html>' "
http://api-dev.freme-project.eu/current/e-terminology/tilde?source-lang=en&target-lang=nl
"

I don't get the its-term-info-ref attribute.


2016-07-18 17:49 GMT+02:00 katia-vistatec <notifications@github.com>:

**Comment by katia-vistatec** [comment]
Yes. Because the version of internationalization declared in freme-parent (0.4) inside <dependencyManagement> element, as default version it is not the version of internationalization on which I made the change and currently on the server. So it doesn't take the code I pushed on the repository.

**Comment by fsasaki** [comment]
Ah, I see. So this is an issue with the built of FREME on the dev server.
Jan can probably fix that tomorrow.

2016-07-18 18:04 GMT+02:00 katia-vistatec <notifications@github.com>:

**Comment by katia-vistatec** [comment]
Yes.

**Comment by jnehring** [comment]
I think I found the version problem. freme-parent determines the version numbers that are used all over FREME. the current version of freme-parent (0.9-SNAPSHOT) defined internationalization to be in version 0.4. Your changes that implement this fix are not implemented in 0.4 but in 0.5-SNAPSHOT.

I changed the version of internationalization to 0.5-SNAPSHOT. When I repeat [fsasakis curl request](https://github.com/freme-project/basic-services/issues/56#issuecomment-233373196) then I get this output:

```
<!DOCTYPE html>
<html U000022U000027enU000027="" lang="&quot;">
    <head>
        <meta charset="UTF-8">
            <title>Example</title>
        </head>
        <body>
            <h1>Example</h1>
            <p>Welcome to the capit
                <span its-term-info-ref="
                    <http://freme-project.eu/#char=36,43>" its-term="yes">capital
                    </span>ermany!
                </p>
            </body>
```

There is a span-its-term-info-ref attribute. But the text does not get merged correctly, some parts are being stripped. This looks like the same problem as #60

**Comment by katia-vistatec** [comment]
Hi,
I have pushed the changes to the repository. See also #60.

**Comment by fsasaki** [comment]
Looks good! Just one item: in its-term-info-ref you won't need &lt;>, that is instead of
> &lt;span its-term-info-ref="&lt;http://freme-project.eu/#char=36,40>" its-term="yes">city                &lt;/span>

You would have

> &lt;span its-term-info-ref="http://freme-project.eu/#char=36,40" its-term="yes">city                &lt;/span>

**Comment by jnehring** [comment]
Works fine! @fsasaki can you please test and close the issue when everything is fine?

**Comment by fsasaki** [comment]
Works fine, thanks.
