### ISSUE TITLE
[e-Internationalization] request does not finish

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#59]
When I try to submit a longer request with [SB50.txt](https://github.com/freme-project/e-services/files/304723/SB50.txt) then the request never finishes.

```
curl -X POST --header "Content-Type: text/html" --data "@SB50.html" "http://api-dev.freme-project.eu/current/toolbox/nif-converter?outformat=turtle"
```

**Comment by jnehring** [comment]
When this issue is finished, we can test https://github.com/freme-project/e-services/issues/14 again. I think the API call from this issue is also affected by this bug.

**Comment by katia-vistatec** [comment]
Hi,
for this I have found the problem.

**Comment by jnehring** [comment]
Did you fix the problem? It seems to me that the response time is still very long.

**Comment by katia-vistatec** [comment]
I am fixing now.

**Comment by katia-vistatec** [comment]
Pushed changes to repository.

**Comment by katia-vistatec** [comment]
Now It seems to work.

**Comment by jnehring** [comment]
Great! The response time is really fast now. So we can close the issue.
