### ISSUE TITLE
[e-internalisation] HTML annotations wrongly merged

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#60]
With the attached input I get the attached output. The output has some wrongly merged and repeated text, and the string "undefined" appears.
[html-output.txt](https://github.com/freme-project/basic-services/files/361998/html-output.txt)
[html-input.txt](https://github.com/freme-project/basic-services/files/361999/html-input.txt)

**Comment by fsasaki** [comment]
any news on this, @katia-vistatec ? Is this depending on a separate issue?

**Comment by katia-vistatec** [comment]
[test.txt](https://github.com/freme-project/basic-services/files/373671/test.txt)

**Comment by katia-vistatec** [comment]
Hi Felix,
in case I have in the original html <p>city</p>, the span of the enrichment is not applied. Should it appear?I have attached the file for input and output.

**Comment by fsasaki** [comment]
> Should it appear?

Yes, I think so.

**Comment by katia-vistatec** [comment]
Hi Felix,
I have pushed the changes to the repository.

**Comment by fsasaki** [comment]
looks good, thanks!
