### ISSUE TITLE
[XSLT Converter] Dummy title

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#63]
Sending this XML to the XSTL Converter

```
<xliff version='2.0' xmlns='urn:oasis:names:tc:xliff:document:2.0'
	srcLang='en' trgLang='fr'>
	<file id='f1'>
		<unit id='u1'>
			<segment>
				<source>We very much welcome you in the city of Prague, a home of
					XML!</source>
			</segment>
		</unit>
	</file>
</xliff>
```

produces this HTML

```
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>
      <title>dummy title</title>
   </head>
   <body>
      <div id="xyz1xyz">
         <p id="n1">We very much welcome you in the city of Prague, a home of XML.</p>
      </div>
   </body>
```

I am not sure why it produces "dummy title". Wouldnt it be better to leave the title empty?

CURL to reproduce:

```
curl -X POST --header "Content-Type: text/xml" --header "Accept: text/html" -d "<xliff version='2.0' xmlns='urn:oasis:names:tc:xliff:document:2.0' srcLang='en' trgLang='fr'> <file id='f1'>  <unit id='u1'>   <segment>   <source>We very much welcome you in the city of Prague, a home of XML.</source>   </segment>  </unit> </file></xliff>" "http://api-dev.freme-project.eu/current/toolbox/xslt-converter/documents/xliff20-to-html"
```

**Comment by fsasaki** [comment]
Yes, makes sense. On the other hand an HTML validator creates an error if
the "title" element is empty. The XSLT processor used in FREME deploys the
HTML parsing / validation library validator.nu for processing HTML input
with XSLT. That is the reason why "title" has some dummy content. But maybe
it should be marked more explicitly.

2016-07-14 10:22 GMT+02:00 Jan Nehring <notifications@github.com>:

**Comment by jnehring** [comment]
ok thanks for the clarification. When the dummy title is needed then we should let it where it is.
