### ISSUE TITLE
[e-internationalisation] embedded XML is escaped

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#70]
See attached curl request. The embedded XML is escaped after processing, e.g. 
>  &lt;file id="f1">

becomes
> &amp;lt;file id="f1">

This creates issues for further processing of the embedded XML. Can the escaping be avoided?

[curl.txt](https://github.com/freme-project/basic-services/files/385414/curl.txt)

**Comment by jnehring** [comment]
I think the content of `<script>` tags should not be changed by e-internationalization. No matter if it is `<script type="application/xml">` script or another type.

**Comment by jnehring** [comment]
The issue is solved. Thank you!
