### ISSUE TITLE
[Users] Add PUT user endpoint

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#72]
Create an API endpoint that allows changing a users password. The user needs to be authenticated to change his own password. Admin user can change all passwords.

**Comment by ArneBinder** [comment]
This is implemented and documented in the authentication article and the interactive api doc.

**Comment by ArneBinder** [comment]
@jnehring please review the [authentication article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/authentication.html#optional-how-to-change-the-password-of-a-user) and the [api doc](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/User/put_user_username).

**Comment by jnehring** [comment]
This does not look right to me. It says

> To do so, you have to use an access token of the user you want to delete or from the admin.

It is about deletion? 

Further there is still a bug in this functionality (#76)

**Comment by ArneBinder** [comment]
The article is fixed. @jnehring Can we close this? The bug should be handled by #76.

**Comment by jnehring** [comment]
We can close this, the bug will be further followed in #76
