### ISSUE TITLE
[e-Internationalization filter] add parameter to switch on / off e-Internationalization

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#73]
e-Internationalization becomes active when the Content-Type header is text/html. This can also be the case when the XSLT converter is used to convert from html to xml. In this case e-Internationalization should not become active.

To overcome this problem please add a parameter useI18n with possible values true, false or undefined, with undefined being the default value. The parameter has the following effect:

* true: e-Internationalization will become active in any case, also when the blacklist switches off e-Internationalization for a specific endpoint.
* false: e-Internationalization does not become active. To overcome the behaviour described above you have to set useI18n=false
* undefined: Implements the current behaviour.

This behaviour needs to be described in [e-Internationalization article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/eInternationalisation.html) and [XSLT article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/xslt-transformation.html).

**Comment by ArneBinder** [comment]
I added a **Note** to the first paragraph of the [internalization article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/eInternationalisation.html) @jnehring please review it.

**Comment by jnehring** [comment]
Thank you it looks good. Just a few remarks:

* The parameter should have three values true, false and undefined. The documentation (both API doc and the article) note only true and false. Please write about all three values.
* The API doc does not provide a default value. It should be "undefined".
* The data type of the parameter is "string" and not undefined in the API doc

**Comment by ArneBinder** [comment]
I modified the Note in the e-Internalization article and added the default value `undefined` to the swagger. @jnehring please have a look.

**Comment by jnehring** [comment]
great thanks
