### ISSUE TITLE
[Pipelines] e-Internationalization in pipelines

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#74]
To enable roundtripping in pipelines the pipelines implement a certain logic [here](https://github.com/freme-project/basic-services/blob/master/controllers/pipelines/src/main/java/eu/freme/bservices/controllers/pipelines/core/PipelineService.java#L71).

Task 1: Currently this works only for HTML. It should work for all e-Internationalization formats. The formats for roundtripping should move to e-Internationalization.

Task 2: This behaviour becomes active depending on content-type header of the first pipeline step and the accept header of the last pipeline step. When XSLT converters that process HTML are used then this can cause problems because both headers are text/html but e-Internationalization should not become active. To overcome this problem the parameter created in #73 should switch off e-Internationalization in the pipelines API also. This behaviour should be noted in the [XSLT converter article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/xslt-transformation.html), [pipelines tutorial](http://api-dev.freme-project.eu/doc/tutorials/pipeline-entity-link.html) and in the interactive api doc.

**Comment by ArneBinder** [comment]
This is implemented.
I added content to the `Step 3` of the [pipeline tutorial](http://api-dev.freme-project.eu/doc/tutorials/pipeline-entity-link.html#) and the parameter `useI18n` to the pipeline endpoints in the api doc, @jnehring please review.

**Comment by jnehring** [comment]
Ok! There are some remarks about documentation in #73 so we can close this issue.
