### ISSUE TITLE
[nifconverter] add tika

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#75]
[Apache Tika](https://tika.apache.org/) will be integrated into the nifconverter in order to support more input formats. Using Tika the nifconverter can convert [many formats](https://tika.apache.org/1.13/formats.html) to NIF, e.g. PDF, all MS Office formats and many more.

**Comment by jmschnei** [comment]
The Apache TIKA functionality has been added in the nif-converter endpoint. There are also two tests for validating it with MSWord and PDF files.

**Comment by fsasaki** [comment]
Great work! Do you have a sample CURL request?

Best,

Felix

2016-08-08 13:45 GMT+02:00 Julian Moreno Schneider <notifications@github.com

**Comment by jmschnei** [comment]
The curl request is:

curl -X POST -d @../src/data.pdf "http://localhost:8080/toolbox/nif-converter?informat=TIKAFile" -H "Accept: text/turtle"

The localhost should be modified using the server URL.

**Comment by jnehring** [comment]
How does tika determine the data format of the file? Depending on the file ending?

**Comment by jnehring** [comment]
I installed the codes on freme-dev. They do not work. This CURL

```
curl -X POST -d @source_pdf.pdf "http://api-dev.freme-project.eu/current/toolbox/nif-converter?informat=TIKAFile" -H "Accept: text/turtle"
```

produces

```
{
  "exception": "eu.freme.common.exception.BadRequestException",
  "path": "/toolbox/nif-converter",
  "message": "There is no file because it is not a multipart request",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1471333818984
}
```

What is wrong?

Another question: Did you write documentation about this in the DKT documentation somewhere that we can reuse in the FREME documentation?

**Comment by jmschnei** [comment]
The problem is that the endpoint expects a Multipart Request. In order to perform it using CURL it should be specified the -F/--form parameter. This is a working request.

curl -X POST -F "inputFile=@source_pdf.pdf" "http://api-dev.freme-project.eu/current/toolbox/nif-converter?informat=TIKAFile" -H "Accept: text/turtle"

The file format is automatically determined by TIKA and the supported formats can be found in:

[https://tika.apache.org/1.13/formats.html](https://tika.apache.org/1.13/formats.html)

**Comment by jnehring** [comment]
Thank you. I added support for the prefix parameter to the nif converter.

**Comment by fsasaki** [comment]
@jnehring , will this functionality be added to the documentation of the NIF converter
http://api-dev.freme-project.eu/doc/api-doc/full.html#!/Toolbox/NIF-Converter
?

**Comment by jnehring** [comment]
Thanks for the reminder. The documentation issue got lost somehow. I created a new issue: https://github.com/freme-project/freme-project.github.io/issues/284

**Comment by fsasaki** [comment]
I tried 

>  curl -X POST -H "Content-Type: text/html" -d '' "http://api-dev.freme-project.eu/current/e-terminology/tilde?informat=text/html&source-lang=de&target-lang=en&filter=count-domains&intype=url&input=http://www.zeit.de/wirtschaft/2016-09/arbeitskraeftepotenzial-deutschland-ungenutzt-arbeit-wille"

and it works. If I try the same with the informat TIKAFile, I get

>  "parameter informat has invalid value \"TIKAFile\"

It would be great to be able to use TIKA without having to call explicitly the NIF conversion endpoint. Is that feasible?

**Comment by jnehring** [comment]
I created a new issue for this: #107

I hope we can find the time to implement this.
