### ISSUE TITLE
[Pipelines] Allow parametrization

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#77]
Please allow query string parameters in the pipelines. An example is this pipeline:
```
[
{
  "method": "POST",
  "endpoint": "http://dev.digitale-kuratierung.de/api/e-nlp/namedEntityRecognition",
  "parameters": {
     "models": "$models$", 
     "language": "$language$",
     "analysis": "ner",
     "mode": "all"
  },
  "headers": {
    "content-type": "text/plain",
    "accept": "text/turtle"
  },
  "body": "The summer of 2016 is not very hot in Berlin. Wolfgang Rossi, weather reporter of the German Tagesschau, added that the summer of 1983 was much better."
}
]
```

A user can then perform an API request like this:

```
http://api.freme-project.eu/current/pipelining/chain?language=en&models=ModelEN
```

The system will then insert the parameters in the pipeline. Some more properties of the system:

* When a pipeline contains parameters which are not set via the query string then the endpoint should return status code 400 - bad request with a proper error message.
* This function should be available for both pipeline endpoints.

**Comment by jnehring** [comment]
This functionality should be available for

* parameters
* headers
* endpoint

It should also be possible to set a parameter like this: "endpoint": "http://abc$param$"
Further it should be able to escape the `$` sign.

**Comment by ArneBinder** [comment]
@jnehring this is implemented, please have a try.

**Comment by fsasaki** [comment]
Sorry, jumping in :)

it works, see below:

curl -X POST -H "Content-Type: text/xml" -d '<xliff version="2.0"
xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en"
trgLang="fr"><file id="f1">  <unit id="u1">   <segment>  <source>We very
much welcome you in the city of Prague, a home of XML!</source> </segment>
</unit></file></xliff>' "
http://api-dev.freme-project.eu/current/pipelining/chain/75?stats=false&language=en&useI18n=false
"

The language parameter is set in the pipeline template
http://api-dev.freme-project.eu/current/pipelining/templates/75

One issue, not specific to the parameters but pipelining in general (?),
may be error messages. E.g. if I set a language that does not exist, I get
as output

Unexpected '<'

I don't get the error message that the language does not exist. If I make
the API call independent of pipelining, see e.g.
http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?language=ex&dataset=dbpedia
I get a proper error message.

{
  "exception": "eu.freme.common.exception.BadRequestException",
  "path": "/e-entity/freme-ner/documents",
  "message": "Unsupported language.",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1471372173831
}

Does this have to do with the parameters or the pipelining in general? If
the later we can have a separate issue on this.

**Comment by ArneBinder** [comment]
This is a general pipeline issue. I could reproduce the error when calling without parametrization. Try:

```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 7a1672a6-b814-e4cf-a628-c14554c8a0cc" -d '[ {
    "method" : "POST",
    "endpoint" : "http://api-dev.freme-project.eu/current/toolbox/xslt-converter/documents/xliff20-to-html",
    "parameters" : { },
    "headers" : {
      "content-type" : "text/xml",
      "accept" : "text/xml"
    },
    "body" : "<xliff version=\"2.0\" xmlns=\"urn:oasis:names:tc:xliff:document:2.0\" srcLang=\"en\" trgLang=\"fr\"><file id=\"f1\"> <unit id=\"u1\"> <segment> <source>We very much welcome you in the city of Prague, a home of XML!<\/source> <\/segment> <\/unit><\/file><\/xliff>"
  }, {
    "method" : "POST",
    "endpoint" : "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?dataset=dbpedia&mode=all",
    "parameters" : {
      "language" : "ex"
    },
    "headers" : {
      "content-type" : "text/html",
      "accept" : "text/html"
    },
    "body" : null
  }, {
    "method" : "POST",
    "endpoint" : "http://api-dev.freme-project.eu/current/toolbox/xslt-converter/documents/html-to-xliff20",
    "parameters" : { },
    "headers" : {
      "content-type" : "text/html",
      "accept" : "text/xml"
    },
    "body" : null
  } ]' "http://api-dev.freme-project.eu/current/pipelining/chain?useI18n=false"
```

**Comment by fsasaki** [comment]
Thanks - I created
https://github.com/freme-project/basic-services/issues/81
to keep track of this.

2016-08-16 21:03 GMT+02:00 ArneBinder <notifications@github.com>:

**Comment by ArneBinder** [comment]
Can we close this?

**Comment by jnehring** [comment]
I will test this

**Comment by jnehring** [comment]
This cURL fails

```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: ca0a3ca9-706f-c780-5d60-f1533cf74feb" -d '[
{
  "method": "POST",
  "endpoint": "http://dev.digitale-kuratierung.de/api/e-nlp/namedEntityRecognition",
  "parameters": {
     "models": "ner-wikinerEn_LOC;ner-wikinerEn_ORG;ner-wikinerEn_PER", 
     "language": "$language$",
     "analysis": "ner",
     "mode": "all"
  },
  "headers": {
    "content-type": "text/plain",
    "accept": "text/turtle"
  },
  "body": "The summer of 2016 is not very hot in Berlin. Wolfgang Rossi, weather reporter of the German Tagesschau, added that the summer of 1983 was much better."
},
{
  "method": "POST",
  "endpoint": "http://dev.digitale-kuratierung.de/api/e-nlp/namedEntityRecognition",
  "parameters": {
     "models": "englishDates", 
     "language": "$language$",
     "analysis": "temp"
  },
  "headers": {
    "content-type": "text/turtle",
    "accept": "text/turtle"
  }
}
]' "http://api-dev.freme-project.eu/current/pipelining/chain?language=en"
```

with error message

```
{
  "exception": "eu.freme.common.exception.BadRequestException",
  "path": "/pipelining/chain",
  "message": "Missing parameter(s) to process the string: '$language$'. Please specify value(s) for the following parameter(s): language",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1471509718083
}
```

What is wrong with the cURL?

**Comment by ArneBinder** [comment]
Should be fixed.

**Comment by jnehring** [comment]
Thanks. This works now. Last think to do: Please add a paragraph in the pipeline tutorial to document this: http://api-dev.freme-project.eu/doc/tutorials/pipeline-entity-link.html

**Comment by ArneBinder** [comment]
The documentation issue moved to https://github.com/freme-project/freme-project.github.io/issues/289. @jnehring can we close this?

**Comment by jnehring** [comment]
this issue is finished
