### ISSUE TITLE
pipelines with XSLT and XML / HTML processing

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#78]
I am trying to reproduce the pipeline discussed at
https://github.com/freme-project/basic-services/issues/64#issuecomment-236097614
see the attachment 
https://github.com/freme-project/basic-services/files/389927/pipeline.zip
which gives the list of requests in CURL. @ArneBinder had created a pipeline that implements this, see
https://github.com/freme-project/basic-services/issues/64#issuecomment-236165400
but the pipeline http://api-dev.freme-project.eu/current/pipelining/templates/69 seems to be gone.
I was trying to reproduce it but failed. The new useI18n parameter https://github.com/freme-project/basic-services/issues/73 may influence how the pipeline should look like.  A special aspect of the pipeline is that some steps should use e-Internationalisation with HTML input and XML output (e.g. FREME-NER), but others (XSLT steps) should not use e-Internationalisation.

**Comment by ArneBinder** [comment]
I think it is gone because of the persist parameter. But I dont understand its description (in the api-doc):

> persist: if false, the template will not automatically be deleted; if false it will live only for one week.

What is the id of your newly created pipeline? So I could have a look at it. 

If you use any pipeline with xslt-converters now you have to submit 'useI18n=false' when you execute the pipeline to suppress e-Internalization.

**Comment by fsasaki** [comment]
I have not yet uploaded the new pipeline. @jnehring kindly created a pipeline which works on freme live, but not freme dev, see https://github.com/freme-project/basic-services/issues/79

as Jan wrote

> It is ok when you do this when you are back in the office

no hurry :)

**Comment by jnehring** [comment]
@fsasaki can we close this?

**Comment by fsasaki** [comment]
yes, thanks.
