### ISSUE TITLE
Implement example pipelines

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#86]
Please implement example  pipelines for the semantics tutorial. The pipeline should enrich english test. Please create a postman collection that executes all these requests against the live api and attach the collection to this GitHub issue.

### pipeline 1: Enrichment pipeline

1. /e-entity/freme-ner/documents
2. /e-terminology/tilde
3. /e-translation/tilde
4. /e-link/documents (please choose a template that adds data from the example document)

### Pipeline 2: Detect Entities in HTML content

1. NIF converter from HTML to NIF. It should fetch the content of a web page using the new intype parameter. Please find an example web page in English with some nice example. The example should not be too long so the processing time is not too long.
2. Enrich this using DBPedia

### Pipeline 3: Enrich HTML and merge annotations back in HTML

1. Use nif-converter to convert short example HTML to NIF
2. enrich with e-entity, outformat is HTML

### Pipeline 4: Change outformat using the postprocessing filter

1. /e-entity/freme-ner/documents
2. use filter entities-detailed-info

### Pipeline 5: XSLT converter pipeline

I will add the example

**Comment by bgrusdt** [comment]
[pipeline1.txt](https://github.com/freme-project/basic-services/files/436562/pipeline1.txt)

**Comment by bgrusdt** [comment]
[pipeline2.txt](https://github.com/freme-project/basic-services/files/436750/pipeline2.txt)
[pipeline3.txt](https://github.com/freme-project/basic-services/files/436751/pipeline3.txt)
[pipeline4.txt](https://github.com/freme-project/basic-services/files/436752/pipeline4.txt)

**Comment by bgrusdt** [comment]
[pipeline4.txt](https://github.com/freme-project/basic-services/files/436780/pipeline4.txt)
the output - format text/csv in the last step doesn't work yet

**Comment by jnehring** [comment]
Thank you!
* when executing pipeline 3 i get an internal server exception.
* please use freme ner instead of dbpedia spotlight in pipeline 2 because i think freme ner is more reliable
* Here is the example for the xslt converter pipeline, please change it to freme-live
* When these things are done, please create the postman collection

```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 540d33d4-7983-bb24-f2f7-73671c80e1cb" -d '  [
      {
  "method": "POST",
    "endpoint": "http://api-dev.freme-project.eu/current/toolbox/xslt-converter/documents/xliff20-to-html",
    "headers": {
      "Content-Type": "text/xml",
      "Accept": "text/xml"
    },
    "body": "<xliff version=\"2.0\" xmlns=\"urn:oasis:names:tc:xliff:document:2.0\" srcLang=\"en\" trgLang=\"fr\">\n    <file id=\"f1\">\n        <unit id=\"u1\">\n            <segment>\n                <source>We very much welcome you in the city of Prague, a home of XML!</source>\n            </segment>\n        </unit>\n\t  <unit id=\"u2\">\n            <segment>\n                <source>We very much welcome you in the city of Berlin, a home of JSON!</source>\n            </segment>\n\t      <unit id=\"u3\">\n            <segment>\n                <source>We very much welcome you in the city of London, a home of RDF!</source>\n            </segment>\n        </unit>\n        </unit>\n    </file>\n</xliff>\n"
  },
  {
    "method": "POST",
    "endpoint": "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all",
    "headers": {
      "Content-Type": "text/html",
      "Accept": "text/html"
    }
  },
  {
      "method": "POST",
      "endpoint": "http://api-dev.freme-project.eu/current/toolbox/xslt-converter/documents/html-to-xliff20",
      "headers": {
          "Content-Type": "text/html",
          "Accept": "text/xml"
      }
  }
]' "http://api-dev.freme-project.eu/current/pipelining/chain?useI18n=false"
```

**Comment by bgrusdt** [comment]
This is pipeline 3 with html in the body instead of loading it with the intype parameter: 
```
[{
[{
		"method": "POST",
		"endpoint": "http://api.freme-project.eu/current/toolbox/nif-converter/",

		"headers": {
			"content-type": "text/html",
			"accept": "text/turtle"
		},
		"body": "<p>This summer the Olympic Games took place in Brazil.</p>"
		
		
	}, 
	{
		"method": "POST",
		"endpoint": "http://api.freme-project.eu/current/e-entity/freme-ner/documents/",
		"parameters": {
			"language": "en",
			"dataset" : "dbpedia",
			"mode": "all"
		},
		"headers": {
			"content-type": "text/turtle",
			"accept": "text/html"
		}
	}

]

```

**Comment by bgrusdt** [comment]
Wait for #88, #89, #90

**Comment by jnehring** [comment]
Please create the Postman collection despite the other issues. You can leave out pipeline 5. When #88 and #89 are a problem somewhere then just do not use the intype parameter and submit HTML directly in the pipeline.

**Comment by bgrusdt** [comment]
Here is the Postman Collection. It does not contain pipeline 5. 
[Enrichment%20Pipelines.postman_collection.json.zip](https://github.com/freme-project/basic-services/files/442215/Enrichment.20Pipelines.postman_collection.json.zip)

**Comment by jnehring** [comment]
Thank you
