### ISSUE TITLE
[XSLT converter] errors during stylesheet compilation

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#90]
This cURL

```
curl -X POST -H "Content-Type: text/html" -H "Cache-Control: no-cache" -H "Postman-Token: 09e5688e-ade3-f429-7458-22ed9b34a69c" -d '<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en" trgLang="fr">
    <file id="f1">
        <unit id="u1">
            <segment>
                <source>We very much welcome you in the city of Prague, a home of XML!</source>
            </segment>
        </unit>
	  <unit id="u2">
            <segment>
                <source>We very much welcome you in the city of Berlin, a home of JSON!</source>
            </segment>
	      <unit id="u3">
            <segment>
                <source>We very much welcome you in the city of London, a home of RDF!</source>
            </segment>
        </unit>
        </unit>
    </file>
</xliff>
' "http://api-dev.freme-project.eu/current/toolbox/xslt-converter/documents/xliff20-to-html"
```

produces

```
{
  "exception": "eu.freme.common.exception.FREMEHttpException",
  "path": "/toolbox/xslt-converter/documents/xliff20-to-html",
  "message": "Errors were reported during stylesheet compilation",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1472133874474
}
```

**Comment by ArneBinder** [comment]
I fixed the init-xsltconverter...sql scripts (had to remove all `\r`) and updated [the converter at freme-dev](http://api-dev.freme-project.eu/current/toolbox/xslt-converter/manage/xliff20-to-html). I'm not sure about [the converter at live](http://api.freme-project.eu/current/toolbox/xslt-converter/manage/xliff20-to-html), it still looks different than the dev version.

**Comment by fsasaki** [comment]
> @fsasaki can we replace the version at live (which can not not be compiled and I could not find the error) with the one at freme-dev?

yes, we can do that, thanks.

**Comment by ArneBinder** [comment]
I updated the converter at live. But because of some bug fixes which are not released yet, the output of the request above is still incorrect at live. Nevertheless, @jnehring can we close this?

**Comment by jnehring** [comment]
I leave it open so I can test it at next release.

**Comment by jnehring** [comment]
This works after the release
