### ISSUE TITLE
authentification seems not to work

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#91]
I cannot do authentification, i.e. I cannot get a token, on freme-dev. I am user fsasaki .

**Comment by jnehring** [comment]
I created an auth token for the admin user and this worked. Unfortunately I cannot ask you to post the curl request here because this would reveal your password. We should try it together. We can also reset your password, maybe this is the problem.

**Comment by fsasaki** [comment]
We can close this, after discussion with @jnehring I learnt that this is an issue with the documentation.
