### ISSUE TITLE
[XSLT converter] problems on freme-live

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#94]
I tried the tei2temp-html converter and it did work on freme-dev and it did not work on freme-live. So I replaced the filter on live with the one from dev and now it works on live.

Then I found out that the "identity-transformation" filter does work on dev and not work on live. This problem could not be solved by copying the filter.

Further the converter xliff20-to-html causes problems both on freme-dev and freme-live, more info here in #87

I could not test `xslt-30-test` and `xslt-with-param` because I do not have test input files.

**Comment by jnehring** [comment]
Maybe related to #90 ?

**Comment by jnehring** [comment]
Please create a table

| converter | freme-dev | freme-live |
| --- | --- | --- |
| xslt20-to.html | works | does not work |
| ... | works | does not work |

When something does not work please check if this is due to outdated data or what is the problem.

**Comment by ArneBinder** [comment]
I added some example requests (including example input data) to [the postman collection](https://api-dev.freme-project.eu/doc/resources/postman/FREME.postman_collection.json), but we still need example input for `xslt-30-test`.

**Comment by jnehring** [comment]
\r should be no problem.

It is odd that the converters work on dev and do not work on live because the xslt converter source code did not change since the last release. But maybe this is some side effect with e-Internationalization or something similar.

Because if html-xliff20 i created #103

**Comment by jnehring** [comment]
The converts still dont work on freme-live

**Comment by ArneBinder** [comment]
@jnehring the reason is that `/toolbox/xslt-converter/.*` is not in the `freme.einternationalization.endpoint-blacklist` of freme-live.

**Comment by jnehring** [comment]
thanks i will try this.

**Comment by jnehring** [comment]
I added the configuration. Now tei2temp-html, identity-transformation, html-xliff-20, xliff20-to-html work. xslt-with-param does not work. I raised #110 for xslt-with-param, this issue is finished
