### ISSUE TITLE
[internationalization-filter] add nif-version parameter

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#98]
Already implemented in internationalziation, needs to be put in internationalization filter now.

**Comment by jnehring** [comment]
This is implemented. @katia-vistatec I dont know how to test, can you please verify? In a break point debugger I can see that the correct parameter is passed from internationalization-filter to internationalization.

**Comment by katia-vistatec** [comment]
Which is the problem? What do I have to test?

**Comment by jnehring** [comment]
Now the nif-version parameter gets forwarded from the internationalization-filter to internationalization. But I do not know what to look for or how to test it.

**Comment by katia-vistatec** [comment]
in internationalization or internationalizations filter?

**Comment by katia-vistatec** [comment]
The parameter needs to be forwarded for the method convertBack() too because I have introduced nifVersion parameter for this method too.

**Comment by jnehring** [comment]
Ok I will implement this

**Comment by jnehring** [comment]
I added the new parameter. But the unit tests of internationalization-filter fail. I do not know what is wrong. @katia-vistatec  can you please check? I think I set the parameter correctly. Currently the tests do not set the parameter, therefore they use nif-version 2.0

The codes are located in a new branch "nif-version".

**Comment by katia-vistatec** [comment]
Ok

**Comment by katia-vistatec** [comment]
The problem seems to be the use of prefix with the version information @prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core/2.0> .
When it looks for nif:wasConvertedFrom it doesn't find anything and so it gives a null skeleton string and an error. If it can't work using prefix with nif version I create a nif file without specifying the version in the prefix, as before.

**Comment by jnehring** [comment]
I tested this using the nif-converter endpoint:

```
curl -X POST -H "Content-Type: text/plain" -H "Cache-Control: no-cache" -H "Postman-Token: f21c95fe-e977-4959-dadc-1f9d71bc6c01" -d '<p>hello world</p>' "http://api-dev.freme-project.eu/current/toolbox/nif-converter"
```

produces

```
@prefix xsd:   
<http://www.w3.org/2001/XMLSchema#> .
@prefix nif:   
    <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .


        <http://freme-project.eu/#char=0,18>
        a               nif:RFC5147String , nif:Context , nif:String ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "18"^^xsd:nonNegativeInteger ;
        nif:isString    "
            <p>hello world</p>" .
```

This NIF is generated by e-Internationalization from the input html. It should be nif 2.1

**Comment by jnehring** [comment]
i tested again, this works now
